### ISSUE TITLE
Preparation testament + contrat des repartitions devant le notaire

### ISSUE THREAD

**Issue by MangoJazz** [foutoucour/TodoList#22]

**Comment by foutoucour** [comment]
On a fait ca non?

**Comment by MangoJazz** [comment]
ben non, c'est prévu mais pas encore fait

Edith Courtial

*cg Studio Map <http://www.cgstudiomap.org/>*
Dedicated contributor / Contributrice dévouée


2017-06-20 9:59 GMT-04:00 Jordi Riera <notifications@github.com>:
