### ISSUE TITLE
Rassembler des quotes de maçons pour le crépi des fondations

### ISSUE THREAD

**Issue by foutoucour** [foutoucour/TodoList#4]
Points a voir:
* corriger des cernes sur la maçonneries
* ancrages a proteger
* alleges a réparer
* petites fissures sur les fondations
* Crépi sur les fondations et les marches d'entrées

**Comment by foutoucour** [comment]
Je la part de Nicolas:
```
nzin [11:38 AM] 
j'ai 2 adresses:
- Obed, pas cher (vit rive sud btw): 514-573-8194
- un entrepreneur: M. Ali: 514-979-9199

[11:38] 
les2 sont tres bien

[11:38] 
Obed je l'utilise pour les petits travaux, Ali, pour les trucs plus importants (>1j) ou plus generaux
```

**Comment by MangoJazz** [comment]
il ne faut pas que ce soit au black par contre et je mesouviens c'est ce qu'ils font eux.

**Comment by foutoucour** [comment]
De la part de Jean:
```
Maçon : Pascal Plouffe de Historia Maçonnerie 858 rue de la Montagne St-Calixte, Qc J0K 1Z0 -- 438-822-2883 -- historiamaconnerie@hotmail.com
```

**Comment by foutoucour** [comment]
Jacques MAJA 
construction inc
reference de sousmission renovation: 438 877 7223

**Comment by foutoucour** [comment]
Ca va etre fait par le peintre en meme temps que la peinture interieure
